services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: prepuser
      POSTGRES_PASSWORD: preppass
      POSTGRES_DB: prepdb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prepuser -d prepdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://prepuser:preppass@db:5432/prepdb
      DATABASE_SYNC_URL: postgresql://prepuser:preppass@db:5432/prepdb
      REDIS_URL: redis://redis:6379/0
      PISTON_URL: http://piston:2000/api/v2/execute
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      piston:
        condition: service_started
    volumes:
      - ./backend:/app
    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  web:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://16.171.25.238:8000
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://16.171.25.238:8000
    depends_on:
      - api

  piston:
    image: ghcr.io/engineer-man/piston
    ports:
      - "2000:2000"
    restart: unless-stopped

volumes:
  pg_data:
