"""add_oa_patterns

Revision ID: 0a61c01562a3
Revises: d1e4f2a83c90
Create Date: 2026-07-09 05:05:52.266022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a61c01562a3'
down_revision: Union[str, None] = 'd1e4f2a83c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oa_patterns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('mcq_count', sa.Integer(), nullable=True),
    sa.Column('coding_count', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('topic_distribution', sa.JSON(), nullable=True),
    sa.Column('difficulty_mix', sa.JSON(), nullable=True),
    sa.Column('is_sectioned', sa.Boolean(), nullable=True),
    sa.Column('source_urls', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company', 'role', 'level', name='uq_oa_pattern_company_role_level')
    )
    op.create_index(op.f('ix_oa_patterns_company'), 'oa_patterns', ['company'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oa_patterns_company'), table_name='oa_patterns')
    op.drop_table('oa_patterns')
    # ### end Alembic commands ###
