"""Add input_schema and output_type to Problem

Revision ID: 6d78e56da052
Revises: 96d3eb61418c
Create Date: 2026-07-09 20:48:16.464587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d78e56da052'
down_revision: Union[str, None] = '96d3eb61418c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('input_schema', sa.JSON(), nullable=True))
    op.add_column('problems', sa.Column('output_type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'output_type')
    op.drop_column('problems', 'input_schema')
    # ### end Alembic commands ###
