"""add_problem_style_columns

Revision ID: 766928b2a48e
Revises: 52ae00034ad0
Create Date: 2026-07-09 18:38:27.801695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '766928b2a48e'
down_revision: Union[str, None] = '52ae00034ad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('starter_code', sa.Text(), nullable=True))
    op.add_column('problems', sa.Column('driver_code', sa.Text(), nullable=True))
    op.add_column('problems', sa.Column('problem_style', sa.String(length=20), server_default='standard', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'problem_style')
    op.drop_column('problems', 'driver_code')
    op.drop_column('problems', 'starter_code')
    # ### end Alembic commands ###
