"""add multilang code dicts

Revision ID: 96d3eb61418c
Revises: 766928b2a48e
Create Date: 2026-07-09 19:42:30.667556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96d3eb61418c'
down_revision: Union[str, None] = '766928b2a48e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('starter_code_dict', sa.JSON(), nullable=True))
    op.add_column('problems', sa.Column('driver_code_dict', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'driver_code_dict')
    op.drop_column('problems', 'starter_code_dict')
    # ### end Alembic commands ###
