"""Add scheduled events

Revision ID: c2ef760b2e1a
Revises: b3f9c2a_cohorts
Create Date: 2026-07-09 04:24:00.706200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2ef760b2e1a'
down_revision: Union[str, None] = 'b3f9c2a_cohorts'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('join_window_minutes', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'open', 'closed', name='scheduledeventstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_events_slug'), 'scheduled_events', ['slug'], unique=True)
    op.drop_constraint(op.f('cohorts_invite_code_key'), 'cohorts', type_='unique')
    op.add_column('sessions', sa.Column('event_id', sa.String(length=36), nullable=True))
    op.create_unique_constraint('uq_session_event_user', 'sessions', ['event_id', 'user_id'])
    op.create_foreign_key(None, 'sessions', 'scheduled_events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_constraint('uq_session_event_user', 'sessions', type_='unique')
    op.drop_column('sessions', 'event_id')
    op.create_unique_constraint(op.f('cohorts_invite_code_key'), 'cohorts', ['invite_code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_scheduled_events_slug'), table_name='scheduled_events')
    op.drop_table('scheduled_events')
    # ### end Alembic commands ###
